config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tweets#index'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  namespace :administrator do
    resources :tweets, only: [:index]
    resources :lists, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/price.rb
class Price < ApplicationRecord
  has_many :tweet_prices, dependent: :destroy
  has_many :tweets, through: :tweet_prices
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags, dependent: :destroy
  has_many :tweets, through: :tweet_tags
end

app/models/tag2.rb
class Tag2 < ApplicationRecord

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tweet_tags, dependent: :destroy
  has_many :tags, through: :tweet_tags
  mount_uploader :image, ImageUploader
  has_many :tweet_prices, dependent: :destroy
  has_many :prices, through: :tweet_prices
end

app/models/tweet_price.rb
class TweetPrice < ApplicationRecord
  belongs_to :tweet
  belongs_to :price
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/tweet_tag2.rb
class TweetTag2 < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         has_many :comments, dependent: :destroy
         has_many :tweets, dependent: :destroy
         validates :name, presence: true
         validates :profile, length: { maximum: 200 }

         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet

         def already_liked?(tweet)
          self.likes.exists?(tweet_id: tweet.id)
        end
end

app/controllers/administrator/lists_controller.rb
class Administrator::ListsController < ApplicationController

  before_action :admin_user

  def index
    @tweets = Tweet.all
  end

  private
    def admin_user
      redirect_to(root_url) unless current_user.administrator?
    end
end

app/controllers/administrator/tweets_controller.rb
class Administrator::TweetsController < ApplicationController
  before_action :admin_user
 
  def index
    @tweet = Tweet.new
  end

  private
    def admin_user
      redirect_to(root_url) unless current_user.administrator?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected
  def configure_permitted_parameters
    added_attrs = [ :email, :name, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rank_tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(5)
    if params[:search] == nil
      @tweets= Tweet.all.page(params[:page]).per(10)
    elsif params[:search] == ''
      @tweets= Tweet.all.page(params[:page]).per(10)
    else
      @tweets = Tweet.where("backpacker LIKE ? ",'%' + params[:search] + '%').or(Tweet.where("price LIKE ? ", "%" + params[:search] + "%")).page(params[:page]).per(10)
    end
  end
  
  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :lat, :country, :image, :q, :lng, :backpacker,:price, tag_ids: [], price_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/administrator/lists_helper.rb
module Administrator::ListsHelper
end

app/helpers/administrator/tweets_helper.rb
module Administrator::TweetsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrator/tweets/index.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>

<%= form_for @tweet do |f| %>

  
  <%= f.country_select :country %>
  <div class="field">
  <%= f.label :内容 %>
  <%= f.text_field :body, :size => 140 %>
  </div>
  
  <div class="field2">
        <%= f.label :金額 %>
        <%= f.select :price,[["~500円","~500円"],["501円~600円","501円~600円"],["601円~700円","601円~700円"],["701円~800円","701円~800円"],["801円~900円","801円~900円"],["901円~1000円","901円~1000円"],["1001円~1100円","1001円~1100円"],["1101円~1200円","1101円~1200円"],["1201円~1300円","1201円~1300円"],["1301円~1400円","1301円~1400円"],["1401円~1500円","1401円~1500円"],["1501円~","1501円~"]] , :prompt => "選択してください"%>
</div>

<div class="field3">
<%= f.label :旅の形態 %>
<%= f.select :backpacker,[["一人旅","一人旅"],["友達旅","友達旅"],["カップル旅","カップル旅"],["夫婦旅","夫婦旅"],["その他","その他"]] , :prompt => "選択してください"%>
</div>

  <div class="field4">
  <%= f.label :image %>
  <%= f.file_field :image %>
  </div>
  
  <div class="check_box">
  <span>タグ</span>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
   <div>
     <%= tag.label do %>
       <%= tag.check_box %>
       <%= tag.text %>
     <% end %>
   </div>
  <% end %>
  </div>

  <div class="check_box">
    <span>タグ</span>
    <%= f.collection_check_boxes(:price_ids, Price.all, :id, :name) do |price| %>
     <div>
       <%= price.label do %>
         <%= price.check_box %>
         <%= price.text %>
       <% end %>
     </div>
   <% end %>
 </div>


     <%= f.label :lat,"緯度" %>
     <%= f.text_field :lat,:value =>"緯度", id: :lat %>
     <%= f.label :lng,"経度" %>
     <%= f.text_field :lng,:value =>"経度", id: :lng %>
   </div>
 



<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,

  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true // ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>

<%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<div class="search">
 <h3>投稿を検索</h3>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
  <label><%= check_box_tag :search, "一人旅" %> 一人旅</label>
  <label><%= check_box_tag :search, "友達旅" %> 友達旅</label>
  <label><%= check_box_tag :search, "カップル旅" %> カップル旅</label>
  <label><%= check_box_tag :search, "夫婦旅" %> 夫婦旅</label>
  <label><%= check_box_tag :search, "その他" %> その他</label>

  <br>

  <label><%= check_box_tag :search, "~500円" %> ~500円</label>
  <label><%= check_box_tag :search, "501円~600円" %> 501円~600円</label>
  <label><%= check_box_tag :search, "601円~700円" %> 601円~700円</label>
  <label><%= check_box_tag :search, "701円~800円" %> 701円~800円</label>
  <label><%= check_box_tag :search, "801円~900円" %> 801円~900円</label>
  <label><%= check_box_tag :search, "901円~1000円" %> 901円~1000円</label>
  <label><%= check_box_tag :search, "1001円~1100円" %> 1001円~1100円</label>
  <label><%= check_box_tag :search, "1101円~1200円" %> 1101円~1200円</label>
  <label><%= check_box_tag :search, "1201円~1300円" %> 1201円~1300円</label>
  <label><%= check_box_tag :search, "1301円~1400円" %> 1301円~1400円</label>
  <label><%= check_box_tag :search, "1401円~1500円" %> 1401円~1500円</label>
  <label><%= check_box_tag :search, "1501円~" %> 1501円~</label>

  <br>

   <a class='cp_btn'><%= submit_tag "検索する" , class: 'button' %></a>
  <% end %>

 </div>

 <h2>新着一覧</h2>

<div class="tweets-container">


  <% @tweets.each do |t| %>
    
  <div class="tweet">

    <%= image_tag t.image_url, size: "200x300" if t.image? %>

    <br>

    <%= t.body %>

    <br>

    <%= t.backpacker %>

    <br>

    <%= t.price %>

    <br>

    <%= t.country %>
      
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <i class="fas fa-bookmark"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
            <i class="fas fa-bookmark"></i><%= t.likes.count %>
          <% end %>
      <% end %>
      <% else %>
     <i class="fas fa-bookmark"></i><%= t.likes.count %>
      <% end %>

   <br>

      <%= link_to "詳細へ", tweet_path(t.id) %>

   <br>

   
  </div>

    <% end %>
  </div>
  
</div>

  <%= paginate @tweets %>

  <h2>いいねランキング</h2>

  <div class="container">
  <div class="rank1"><h3>１位</h3></div>
  <div class="rank2"><h3>２位</h3></div>
  <div class="rank3"><h3>３位</h3></div>
  <div class="rank4"><h3>４位</h3></div>
  <div class="rank5"><h3>５位</h3></div>
  </div>

  <div class="ranked-tweets">
  <% @rank_tweets.each do |t| %>
    <div class="ranked-posts">
    <%= image_tag t.image_url, size: "200x300" if t.image? %>
    <%= t.body %>

    <br>

    <%= t.backpacker %>

    <br>

    <%= t.price %>

    <br>

    <%= t.country %>
      
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
            <i class="fas fa-bookmark"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
            <i class="fas fa-bookmark"></i><%= t.likes.count %>
          <% end %>
      <% end %>
      <% else %>
     <i class="fas fa-bookmark"></i><%= t.likes.count %>
      <% end %>

   <br>

      <%= link_to "詳細へ", tweet_path(t.id) %>

   <br>
    </div>
  <% end %>
  </div>
  
  



  <h2>地図から探す</h2>
  <div id='map', style ="filter:grayscale(55%);"></div>
  
  <script>
    function initMap() {

      let latlng = new google.maps.LatLng(38.60, 139.5);
  
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 2.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

      <% @tweets.each do |t|%>
        ( function() { 

          let markerLatLng = new google.maps.LatLng({lat: <%= t.lat %>, lng: <%= t.lng %>});
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });

          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= tweet_url(t.id) %>' target='_blank'><%= t.body %></a>"
          });
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
 
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h2>詳細ページ</h2>
<div class="details">
 <div class="show">
  <%= image_tag @tweet.image_url, size: "200x300" if @tweet.image? %>

 <div class="booktitle">
  <%= @tweet.body %>
  </div>

  <div class="backpacker">
  <%= @tweet.backpacker %>
  </div>

  <div class="price">
  <%= @tweet.price %>
  </div>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
          <%= link_to tweet_like_path(@tweet), method: :delete do %>
            <i class="fas fa-bookmark"></i><%= @tweet.likes.count %>
          <% end %>
      <% else %>
          <%= link_to tweet_likes_path(@tweet), method: :post do %>
            <i class="fas fa-bookmark"></i><%= @tweet.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="fas fa-bookmark"></i><%= @tweet.likes.count %>
  <% end %>

 </div>

 <div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%=  @tweet.user.name %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
 </div>

 <%= link_to "Tweet一覧に戻る", tweets_path %>

</div>