config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tweets#index'

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  namespace :administrator do
    resources :tweets, only: [:index]
    resources :lists, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/price.rb
class Price < ApplicationRecord
  has_many :tweet_prices, dependent: :destroy
  has_many :tweets, through: :tweet_prices
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags, dependent: :destroy
  has_many :tweets, through: :tweet_tags
end

app/models/tag2.rb
class Tag2 < ApplicationRecord

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tweet_tags, dependent: :destroy
  has_many :tags, through: :tweet_tags
  mount_uploader :image, ImageUploader
  has_many :tweet_prices, dependent: :destroy
  has_many :prices, through: :tweet_prices
end

app/models/tweet_price.rb
class TweetPrice < ApplicationRecord
  belongs_to :tweet
  belongs_to :price
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/tweet_tag2.rb
class TweetTag2 < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
         has_many :comments, dependent: :destroy
         has_many :tweets, dependent: :destroy
         validates :name, presence: true
         validates :profile, length: { maximum: 200 }

         has_many :likes, dependent: :destroy
         has_many :liked_tweets, through: :likes, source: :tweet

         def already_liked?(tweet)
          self.likes.exists?(tweet_id: tweet.id)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @rank_tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(5)
    if params[:search] == nil
      @tweets= Tweet.all.page(params[:page]).per(10)
    elsif params[:search] == ''
      @tweets= Tweet.all.page(params[:page]).per(10)
    else
      @tweets = Tweet.where("backpacker LIKE ? ",'%' + params[:search] + '%').or(Tweet.where("price LIKE ? ", "%" + params[:search] + "%")).page(params[:page]).per(10)
    end
  end
  
  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :lat, :country, :image, :q, :lng, :backpacker,:price, tag_ids: [], price_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Travel the World by Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

  </head>

  <body>


    <header>
      <h1><%= link_to "Travel the World by Book", tweets_path %></h1>
      <div id="header-hover" class="header-list">
      <ul>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% if user_signed_in? %>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <% end %>
        <li><%= link_to "管理者ページ", administrator_tweets_path %></li>
        <li><a href="http://www.tripforbeginnners.com">管理者のブログ</a></li>
      </ul>
      
      <script>
      $('#header-hover').hover(
    function(){
      $('#header-hover').addClass('animated infinite rubberBand');
    },
    function () {
      $('#header-hover').removeClass();
    }
  );
      </script>
      </div>
    </header>
    <div class="main-visual">
    <div class="animated slideOutDown infinite">
      <h2>本で世界を旅しよう</h2>
    </div>
    </div>
    <main>
      <%= yield %>
    </main>
    </body>
    <footer>
        <p>Copyright © 2020 kusaba.</p>
        </footer>
</html>
    